/* --- The following code comes from e:\programming\lcc\lib\wizard\mdidef.tpl. */
// This are the definitions for all symbols used in menus or string.
#define IDI_FIRST 1
#define IDI_SECOND 2


#define IDI_ROOT 703
#define IDI_CODE 704
#define IDI_KERN 705
#define IDI_BOXI 706
#define IDI_VERI 707
#define IDI_LOAD 708
#define IDI_NVRM 709
#define IDI_UNKNOWNBLOCK 710
#define IDI_MACA 711

#define BMP_TOOLBAREXPORT 10
#define BMP_TOOLBARIMPORT 11


#define IDACCEL 10000
// IDs for the file menu
#define IDM_NEW 200
#define IDM_OPEN 210
#define IDM_SAVE 220
#define IDM_SAVEAS 230
#define IDM_CLOSE 240
#define IDM_REVERT 241
#define IDM_PRINT 250
#define IDM_PRINTSU 260
#define IDM_PAGESETUP 267
#define IDM_PRINTPRE 265
#define IDM_EXIT 270
// Ids for the Edit menu
#define IDM_EDITUNDO	310
#define IDM_EDITCUT	320
#define IDM_EDITCOPY	330
#define IDM_EDITPASTE	340
#define IDM_EDITCLEAR	350
#define IDM_EDITDELETE	360
#define IDM_EDITREPLACE	370
#define IDM_EDITREDO	380
#define IDM_MOVEUP 381
#define IDM_MOVEDOWN 382

// Ids for the Search menu
#define IDM_FIND	700
// Ids for the window menu
#define IDM_WINDOWTILE	410
#define IDM_WINDOWCASCADE 420
#define IDM_WINDOWICONS 430
#define IDM_WINDOWCLOSEALL 440
#define IDM_PROPERTIES	450
#define IDM_ABOUT 500
#define IDM_HELP	510
#define IDMAINMENU 600
#define IDAPPLICON 710
#define IDAPPLCURSOR 810
#define IDS_FILEMENU 2000
#define IDS_HELPMENU 2010
#define IDS_SYSMENU 2030
#define IDM_STATUSBAR 3000
#define IDI_CHILDICON 800
#define IDM_WINDOWCHILD	3010
#define ID_TOOLBAR	5000
#define IDD_ABOUT	100
#define IDD_BLOCKEXPORT 101
#define IDD_BLOCKIMPORT 102
#define IDD_BOXIBLOCK 103
#define IDD_VERIBLOCK 104
#define IDD_CHANGECUSTOMERNUMBER 105
#define IDD_PROPERTIES 106
#define IDD_PROPERTIES_MAIN 107
#define IDD_PROPERTIES_USUAL 108
#define IDD_PROPERTIES_BOXI 109
#define IDD_PROPERTIES_VERI 110
#define IDD_PROPERTIES_ZIMFILE 111
#define IDD_PROPERTIES_MULTIPLE 112

// Ids for "Block" menu
#define IDM_BLOCKIMPORT 606
#define IDM_BLOCKEXPORT 607
#define IDM_BLOCKFIXCHECKSUMS 608

#define IDC_BLOCKEXPORTTYPE 609
#define IDC_BLOCKEXPORTSIZE 610
#define IDC_BLOCKLIST 611
#define IDC_BLOCKEXPORTINCLUDEHEADER 612
#define IDC_BLOCKEXPORTOFFSET 613
#define IDC_BLOCKEXPORTDETAIL 614
#define IDM_BLOCKCREATEVERIBLOCK 615
#define IDBROWSE 616
#define IDC_BLOCKIMPORTAUTODETECT 617
#define IDC_BLOCKIMPORTFILENAME 618
#define IDC_BLOCKIMPORTROOT 619
#define IDC_BLOCKIMPORTCODE 620
#define IDC_BLOCKIMPORTKERN 621
#define IDC_BLOCKIMPORTBOXI 622
#define IDC_BLOCKIMPORTVERI 623
#define IDC_BLOCKIMPORTLOAD 624
#define IDC_BLOCKIMPORTNVRM 625
#define IDC_BLOCKIMPORTMACA 626
#define IDC_BLOCKIMPORTFIRSTBLOCK IDC_BLOCKIMPORTROOT
#define IDC_BLOCKIMPORTLASTBLOCK IDC_BLOCKIMPORTMACA
#define IDM_BLOCKCREATEBOXIBLOCK 627
#define IDC_BOXIOUI 628
#define IDC_BOXISTARTERIMAGESIZE 629
#define IDC_BOXISTARTERMD5 630
#define IDC_BOXIHWV 631
#define IDC_BOXISWV 632
#define IDC_BOXIHWM 633
#define IDC_BOXISWM 634
#define IDC_VERIVERA 635
#define IDC_VERIVERB 636
#define IDC_VERIVERC 637
#define IDC_VERIVERD 638
#define IDC_BLOCKADD 639
#define IDC_BLOCKREMOVE 640
#define IDC_VERIBLOCKSTOADD 641
#define IDM_CUSTOMERNUMBER 642
#define IDC_CUSTOMERNUMBER 643
#define IDM_SELECTALL 644
#define IDAPPLY 645
#define IDC_PROPERTIESTAB 646
#define IDM_TOOLSBATCHCUSTOMERNUMBER 647
#define IDM_TOOLSCREATESFS 648
#define IDC_PROPERTIESLONGINFO 649
#define IDC_PROPERTIESLONGINFOGROUPBOX 650
#define IDC_PROPERTIESTYPE 651
#define IDC_PROPERTIESSIZE 652
#define IDC_PROPERTIESOFFSET 653
#define IDC_PROPERTIESADLER 654
#define IDC_PROPERTIESMD5 655
#define IDC_PROPERTIESFILENAME 656
#define IDC_PROPERTIESNUMBEROFBLOCKS 657
#define IDC_PROPERTIESDIRECTORY 658
#define IDC_PROPERTIESMAGICNUMBER 659
#define IDC_PROPERTIESSOURCE 660
#define IDC_PROPERTIESSOURCEOFFSETLABEL 661
#define IDC_PROPERTIESSOURCEOFFSET 662
#define IDC_BLOCKIMPORTINCLUDEHEADER 663
#define IDM_BLOCKCREATEMACABLOCK 664
